openapi: 3.0.0
info:
  title: Planetary Data System API
  description: |
    Federated PDS API which provides actionable end points standardized
    between the different nodes.
  termsOfService: http://pds.nasa.gov
  contact:
    email: pds-operator@jpl.nasa.gov
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.dev
externalDocs:
  description: Find out more information on the PDS API Specification
  url: https://github.com/NASA-PDS/pds-api-core
servers:
- url: https://virtserver.swaggerhub.com/PDS_APIs/pds_federated_api/0.1.0
  description: SwaggerHub API Auto Mocking
tags:
- name: core
  description: Federated core layer for PDS requests
  externalDocs:
    description: Find out more
    url: http://pds.nasa.gov
paths:
  /capabilities:
    get:
      tags:
      - capabilities
      summary: capabilities api entry point, list the resources provided by the current
        API end-point.
      operationId: capabilities
      responses:
        "200":
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/capabilities'
              example:
              - action: capabilities
                version: 0.1
              - action: collections
                version: 0.1
              - action: products
                version: 0.1
              - action: routes
                version: 0.1
        "404":
          description: capabilities not available
        "500":
          description: Internal server error
      x-openapi-router-controller: swagger_server.controllers.capabilities_controller
  /products:
    get:
      tags:
      - products
      summary: search across all PDS data products, including bundles, collections,
        documentation, and observational products,
      operationId: products
      parameters:
      - name: start
        in: query
        description: offset in matching result list, for pagination
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: limit
        in: query
        description: maximum number of matching results returned, for pagination
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: q
        in: query
        description: search query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: fields
        in: query
        description: returned fields, syntax field0,field1
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: sort
        in: query
        description: sort results, syntax asc(field0),desc(field1)
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: Successful request
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/products'
        "404":
          description: lidvid not found
        "500":
          description: Internal server error
      x-openapi-router-controller: swagger_server.controllers.products_controller
  /products/{lidvid}:
    get:
      tags:
      - products
      summary: URN resolver for lidvid
      operationId: products_by_lidvid
      parameters:
      - name: lidvid
        in: path
        description: lidvid (urn)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
        "404":
          description: lidvid not found
        "500":
          description: Internal server error
      x-openapi-router-controller: swagger_server.controllers.products_controller
  /collections:
    get:
      tags:
      - collections
      summary: request PDS collections
      operationId: get_collection
      parameters:
      - name: start
        in: query
        description: offset in matching result list, for pagination
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: limit
        in: query
        description: maximum number of matching results returned, for pagination
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: q
        in: query
        description: search query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: fields
        in: query
        description: returned fields, syntax field0,field1
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: sort
        in: query
        description: sort results, syntax asc(field0),desc(field1)
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: Successful request
          headers:
            X-Total-Count:
              description: Total number of records maching the request.
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/products'
            text/html:
              schema:
                $ref: '#/components/schemas/products'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorMessage'
      x-openapi-router-controller: swagger_server.controllers.collections_controller
  /routes:
    get:
      tags:
      - routes
      operationId: all_routes
      responses:
        "200":
          description: Successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/routes'
      x-openapi-router-controller: swagger_server.controllers.routes_controller
  /routes/{resource}:
    get:
      tags:
      - routes
      operationId: routes
      parameters:
      - name: resource
        in: path
        description: requested action as a request path, e.g. '/record'
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: version
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: query
        in: query
        description: query parameter on the action, e.g. lidvid urn for a '/records'
          action
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "302":
          description: Successful request, redirect request
      x-openapi-router-controller: swagger_server.controllers.routes_controller
components:
  schemas:
    capabilities:
      type: array
      example:
      - action: capabilities
        version: 0.1
      - action: collections
        version: 0.1
      - action: products
        version: 0.1
      - action: routes
        version: 0.1
      items:
        $ref: '#/components/schemas/capability'
    capability:
      required:
      - action
      - version
      type: object
      properties:
        action:
          type: string
        version:
          type: string
      example:
      - action: collections
        version: 0.1
    routes:
      type: array
      example:
      - resource: /routes
        query: '*'
        url: https://pds.nasa/gov/v1/api
        version: "0.1"
      - resource: /products
        query: urn:nasa:pds:insight_rad:*
        url: https://pds-geosciences.wustl.edu/v0/api
        version: "0.2"
      - resource: /products
        query: urn:nasa:pds:insight_rad:*
        url: https://pds-geosciences.wustl.edu/v0.3/api
        version: "0.3"
      items:
        $ref: '#/components/schemas/route'
    route:
      required:
      - query
      - resource
      - url
      type: object
      properties:
        resource:
          type: string
        query:
          type: string
        url:
          type: string
    products:
      required:
      - data
      - metadata
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/metadata'
        data:
          type: array
          items:
            $ref: '#/components/schemas/product'
      example:
        metadata:
          q: q
          start: 0
          limit: 6
          sort:
          - sort
          - sort
        data:
        - procedures:
          - ref: ref
            description: description
            title: title
            type: type
          - ref: ref
            description: description
            title: title
            type: type
          feature_of_interest:
          - feature_of_interest
          - feature_of_interest
          description: description
          id: id
          type: type
          title: title
          properties:
            key:
            - properties
            - properties
          pds4_label_url: pds4_label_url
        - procedures:
          - ref: ref
            description: description
            title: title
            type: type
          - ref: ref
            description: description
            title: title
            type: type
          feature_of_interest:
          - feature_of_interest
          - feature_of_interest
          description: description
          id: id
          type: type
          title: title
          properties:
            key:
            - properties
            - properties
          pds4_label_url: pds4_label_url
    metadata:
      type: object
      properties:
        q:
          type: string
        start:
          type: integer
        limit:
          type: integer
        sort:
          type: array
          items:
            type: string
      example:
        q: q
        start: 0
        limit: 6
        sort:
        - sort
        - sort
    product:
      required:
      - id
      - update_time
      type: object
      properties:
        id:
          type: string
          description: identifier lidvid of the collection
        type:
          type: string
        title:
          type: string
        description:
          type: string
        procedures:
          type: array
          description: list of instruments or procedures generating the data (for
            concept see https://en.wikipedia.org/wiki/Observations_and_Measurements)
          items:
            $ref: '#/components/schemas/reference'
        feature_of_interest:
          type: array
          description: identifier lidvid of the target of or feature of interest the
            observation (for concept see https://en.wikipedia.org/wiki/Observations_and_Measurements)
          items:
            type: string
        pds4_label_url:
          type: string
        properties:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
      example:
        procedures:
        - ref: ref
          description: description
          title: title
          type: type
        - ref: ref
          description: description
          title: title
          type: type
        feature_of_interest:
        - feature_of_interest
        - feature_of_interest
        description: description
        id: id
        type: type
        title: title
        properties:
          key:
          - properties
          - properties
        pds4_label_url: pds4_label_url
    reference:
      required:
      - name
      - ref
      type: object
      properties:
        title:
          type: string
          description: name to display for the external reference
        ref:
          type: string
          description: external reference, here lidvid urn
        type:
          type: string
          description: type of the external reference, can be displayed as an icon
            for example
        description:
          type: string
          description: longer description for the external reference, can be displayed
            in a tooltip
      description: object describing a reference to a different product. TODO The
        properties should be defined by a standard (xlink, json-ld) to be chosen
      example:
        ref: ref
        description: description
        title: title
        type: type
    errorMessage:
      required:
      - message
      - query
      - resource
      - url
      type: object
      properties:
        url:
          type: string
        resource:
          type: string
        query:
          type: string
        message:
          type: string
      example:
        url: https://pds.nasa.gov/api/1.0/collections
        resource: /collections
        query: q=mission qt 12
        message: query operator gt not supported on field mission

